name: CI

on:
  pull_request:
    branches:
      - "main"
      - "dev*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build (Test)
        run: |
          ./gradlew clean build
