name: CI

on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - "release/*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check PR branch name
        run: ci/scripts/validate_branch_names.sh "${{ github.head_ref }}" "${{ github.base_ref }}"

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build (Test)
        run: |
          ./gradlew clean build
